In [7]:
from util import *
import numpy as np

In [8]:
df = load_data(dt = 'p', name = 2007)

In [5]:
df.head(20)

,date,time,g_active_power,g_reactive_power,voltage,global_intensity,sub_1_kitchen,sub_2_laundry,sub_3_wh_ac
0,1/1/2007,00:00:00,2.580,0.136,241.970,10.600,0.000,0.000,0.0
1,1/1/2007,00:01:00,2.552,0.100,241.750,10.400,0.000,0.000,0.0
2,1/1/2007,00:02:00,2.550,0.100,241.640,10.400,0.000,0.000,0.0
3,1/1/2007,00:03:00,2.550,0.100,241.710,10.400,0.000,0.000,0.0
4,1/1/2007,00:04:00,2.554,0.100,241.980,10.400,0.000,0.000,0.0
5,1/1/2007,00:05:00,2.550,0.100,241.830,10.400,0.000,0.000,0.0
6,1/1/2007,00:06:00,2.534,0.096,241.070,10.400,0.000,0.000,0.0
7,1/1/2007,00:07:00,2.484,0.000,241.290,10.200,0.000,0.000,0.0
8,1/1/2007,00:08:00,2.468,0.000,241.230,10.200,0.000,0.000,0.0
9,1/1/2007,00:09:00,2.486,0.000,242.180,10.200,0.000,0.000,0.0
10,1/1/2007,00:10:00,2.492,0.000,242.460,10.200,0.000,0.000,0.0
11,1/1/2007,00:11:00,2.500,0.000,242.880,10.200,0.000,0.000,0.0
12,1/1/2007,00:12:00,2.494,0.000,242.570,10.200,0.000,0.000,0.0
13,1/1/2007,00:13:00,2.492,0.000,242.410,10.200,0.000,0.000,0.0
14,1/1/2007,00:14:00,2.480,0.000,241.810,10.200,0.000,0.000,0.0
15,1/1/2007,00:15:00,2.478,0.000,241.730,10.200,0.000,0.000,0.0
16,1/1/2007,00:16:00,2.470,0.000,241.290,10.200,0.000,0.000,0.0
17,1/1/2007,00:17:00,2.466,0.000,241.110,10.200,0.000,0.000,0.0
18,1/1/2007,00:18:00,2.456,0.000,240.590,10.200,0.000,0.000,0.0
19,1/1/2007,00:19:00,2.460,0.000,240.830,10.200,0.000,0.000,0.0

In [11]:
test = time_rescale(df,'7D')

Processe begin...

Begin configuring datetime line ...done
Begin dropping bug data ... done

C:\Users\lu\Anaconda3\envs\tf2\lib\site-packages\pandas\core\indexing.py:966: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[item] = s

done

In [12]:
test

,g_active_power,g_reactive_power,voltage,global_intensity,sub_1_kitchen,sub_2_laundry,sub_3_wh_ac
full_time,,,,,,,
2007-01-01,1.152170,0.109718,238.848376,4.885524,1.068856,0.860105,6.093263
2007-01-08,1.422602,0.146245,238.996149,6.068642,2.438457,1.494035,6.925731
2007-01-15,1.639451,0.136597,240.440150,6.968413,2.324901,1.991567,8.086508
2007-01-22,1.517470,0.106522,241.991723,6.397440,1.138506,1.482588,7.149717
2007-01-29,1.137664,0.113477,240.860212,4.792143,0.396925,0.960516,7.437004
2007-02-05,0.970162,0.112586,237.638231,4.189187,1.085813,1.961806,5.512599
2007-02-12,1.632337,0.146270,240.321322,6.901766,1.429067,2.677282,7.090675
2007-02-19,1.320603,0.106851,240.138894,5.560488,0.856122,1.562512,6.212046
2007-02-26,0.904076,0.107258,241.519683,3.827044,0.830952,0.723313,4.123016
2007-03-05,0.806891,0.106489,237.663104,3.494782,0.983730,2.012798,4.062996
2007-03-12,1.272973,0.106568,240.262135,5.386905,1.572817,2.007242,5.842758
2007-03-19,1.532828,0.110405,240.778019,6.445798,1.694116,2.040480,8.163409
2007-03-26,1.450084,0.131234,240.424341,6.134782,0.807242,2.789881,7.361111
2007-04-02,1.170303,0.131447,238.052862,5.022560,1.490675,1.757738,6.026687
2007-04-09,0.842081,0.107211,240.172366,3.588710,0.628968,1.619246,4.171528
2007-04-16,0.886208,0.133414,240.054920,3.833373,1.657143,0.671032,4.539980
2007-04-23,0.795370,0.105807,235.500612,3.503975,0.778701,0.679961,4.627614
2007-04-30,1.335267,0.138063,238.466545,5.708485,1.931749,2.533529,5.955078
2007-05-07,0.968601,0.121814,238.590098,4.167282,1.129960,0.830456,5.278770
2007-05-14,1.024428,0.119391,235.531253,4.462540,1.961905,1.669643,4.994841
2007-05-21,1.007194,0.110750,234.993796,4.361548,1.750099,2.104762,5.111111
2007-05-28,0.920197,0.105346,237.493447,3.965853,1.017857,1.126190,3.985020
2007-06-04,1.013378,0.127851,237.605824,4.387360,1.518603,1.492410,5.560175
2007-06-11,1.161818,0.158884,239.834672,4.985595,1.965972,2.220635,5.878671
2007-06-18,0.512064,0.138882,240.580545,2.285354,0.363763,0.851359,2.654098
2007-06-25,0.980306,0.143343,240.113600,4.234666,1.484076,2.521083,5.441115
2007-07-02,1.163452,0.116480,237.904521,4.959345,0.879663,2.205754,6.550893
2007-07-09,1.010649,0.138131,240.113365,4.343377,1.634975,1.613065,5.379598
2007-07-16,0.650334,0.141988,234.626702,2.919476,1.318087,0.776764,3.309158
2007-07-23,0.630839,0.089054,235.317376,2.791845,0.542262,1.685813,3.088194
2007-07-30,1.021048,0.111770,238.248591,4.358730,1.216667,0.666071,5.236508
2007-08-06,1.055761,0.113394,238.598326,4.526310,1.177183,2.011012,5.887500
2007-08-13,0.696895,0.095327,239.107339,3.001607,0.358433,1.049702,4.980952
2007-08-20,0.835948,0.144861,240.520540,3.618573,1.405199,1.856930,4.419288
2007-08-27,0.885740,0.138814,240.429327,3.801151,1.092262,1.469940,4.888690
2007-09-03,0.889307,0.117560,238.674101,3.839454,1.087333,1.656343,5.353615
2007-09-10,1.107446,0.119036,239.383404,4.743532,1.131349,1.672619,5.835714
2007-09-17,0.894429,0.120376,239.408657,3.865476,1.636905,1.207540,5.061806
2007-09-24,1.173551,0.120606,239.194121,4.997043,1.037408,2.779024,5.866938
2007-10-01,1.111431,0.138645,239.757773,4.764206,1.527381,1.799206,5.242361
2007-10-08,1.157807,0.105737,238.882760,4.949008,1.173810,1.710119,5.444643
2007-10-15,1.191872,0.096979,240.016497,5.033631,1.057738,1.662401,6.800397
2007-10-22,1.097689,0.082758,240.686503,4.651935,0.831316,1.366243,5.624826
2007-10-29,1.273233,0.107559,240.568880,5.370516,0.854960,1.822520,5.691468
2007-11-05,0.812594,0.107821,238.696162,3.504623,1.005853,0.378869,4.667063
2007-11-12,1.504285,0.099512,240.908805,6.309623,1.435417,1.842460,8.262302
2007-11-19,1.321658,0.091641,241.764778,5.544022,1.330191,1.552138,7.247346
2007-11-26,1.330046,0.096668,241.883901,5.588848,0.753150,2.097331,7.347852
2007-12-03,0.838091,0.120684,238.886729,3.625992,0.762302,1.176091,5.082639
2007-12-10,1.486147,0.096026,241.223161,6.239960,1.030655,2.054762,8.114385
2007-12-17,1.544693,0.089493,242.717135,6.432880,1.273142,1.669610,8.316004
2007-12-24,1.888514,0.120793,242.152803,7.888413,2.303075,2.433730,8.441270
2007-12-31,1.539265,0.101067,241.094792,6.455000,0.000000,2.400694,9.771528

In [13]:
df

,date,time,g_active_power,g_reactive_power,voltage,global_intensity,sub_1_kitchen,sub_2_laundry,sub_3_wh_ac
0,1/1/2007,00:00:00,2.580,0.136,241.970,10.600,0.000,0.000,0.0
1,1/1/2007,00:01:00,2.552,0.100,241.750,10.400,0.000,0.000,0.0
2,1/1/2007,00:02:00,2.550,0.100,241.640,10.400,0.000,0.000,0.0
3,1/1/2007,00:03:00,2.550,0.100,241.710,10.400,0.000,0.000,0.0
4,1/1/2007,00:04:00,2.554,0.100,241.980,10.400,0.000,0.000,0.0
...,...,...,...,...,...,...,...,...,...
525595,31/12/2007,23:55:00,1.746,0.204,242.410,7.200,0.000,0.000,18.0
525596,31/12/2007,23:56:00,1.732,0.210,242.420,7.200,0.000,0.000,18.0
525597,31/12/2007,23:57:00,1.732,0.210,242.500,7.200,0.000,0.000,18.0
525598,31/12/2007,23:58:00,1.684,0.144,242.180,7.000,0.000,0.000,18.0
525599,31/12/2007,23:59:00,1.628,0.072,241.790,6.600,0.000,0.000,18.0